# Generated by Django 3.2.13 on 2022-08-14 13:49
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0002_auto_20220808_1124'),
    ]

    operations = [
        TrigramExtension(),
    ]
