# Generated by Django 3.2.13 on 2022-08-20 23:30

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0003_auto_20220814_1349'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['fname', 'iname', 'oname'], name='indexes_emp_fname_1395cf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['country'], name='indexes_emp_country_caf6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['begin'], name='indexes_emp_begin_a3eff6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['end'], name='indexes_emp_end_be87f4_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(django.db.models.functions.text.Upper('additional_info'), name='additional_info_upper_index'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('additional_info'), name='gin_trgm_ops'), name='additional_info_gin_idx'),
        ),
    ]
